### PR TITLE
Update to latest cfn spec

### PR DESCRIPTION
**Pull request by richarddowner**
Hey mate, just an update to the CFN spec.

Not sure where I am suppose to be bumping the nuget version? Just in the Project file for each project?

Let me know if anything else is needed.

Chur

### CODE REVIEW

**Comment by jakejscott** [comment]
Yeah have a look in the `VersionPrefix` of the package.csproj for Humidifier and Humidifier.Json projects. Just bump that. I'll push a new tag which wall cause a package to be published

**Comment by jakejscott** [comment]
Like this commit: https://github.com/jakejscott/Humidifier/commit/dd50f7344c16d1e918eb8b16a242c026a5953f68

**Comment by richarddowner** [comment]
@jakejscott bumped the patch version, if that's all good, otherwise I can change the minor.

Cheers

**Comment by richarddowner** [comment]
🍻 🍻 🍻

**Pull request merged**
